#!/usr/bin/env bash
# The commit subject names a task the backlog actually lists. `M-1.6`.
#
#   scripts/check-commit-msg.sh <file>    the commit-msg hook path
#   scripts/check-commit-msg.sh           checks HEAD instead
#
# Non-negotiable 1 says one task equals one commit equals one change that leaves
# the tree green. This holds the traceable half: history stays resolvable to the
# plan, so `git log` answers "why does this exist" without archaeology.
#
# ## Why the ID must exist in the backlog rather than merely look like one
#
# A regex alone accepts `M-9.99`, which resolves to nothing. The point of the ID
# is the link, and a link to a task nobody wrote is worse than no ID because it
# reads as traceable. So the backlog is the authority and this script does not
# keep its own list.
#
# ## What it deliberately does not check
#
# Whether the commit actually *does* what the task says. No script reads intent,
# and pretending otherwise would make this a rule people route around. That
# belongs to review.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

cd "$REPO_ROOT"

MSG_FILE="${1:-}"

if [[ -n "$MSG_FILE" ]]; then
  [[ -f "$MSG_FILE" ]] || { fail "commit message file not found: $MSG_FILE"; finish; }

  # The subject is the **first non-blank line**, and if that line is a comment
  # the message is refused rather than searched past.
  #
  # ⚠️ This script cannot know which cleanup mode git will apply, and the modes
  # disagree about comments. `git commit` with an editor uses cleanup=strip,
  # which removes them; `-m` and `-F` use cleanup=whitespace, which keeps them.
  # So for `git commit -m '#42 note' -m 'M-1.35: …'` the subject that lands is
  # `#42 note` — and a version of this script that skipped comment lines read
  # the *body* instead, reported `ok … names M-1.35`, and let through a commit
  # naming no task at all. That is the one thing this gate exists to refuse.
  #
  # Guessing cannot be made safe, so the ambiguity is the failure. Refusing also
  # keeps the `commit.verbose` case honest: the appended diff is not
  # comment-prefixed, and searching onward reported `got: diff --git a/f b/f`,
  # a subject the author never wrote.
  #
  # ⚠️ Two earlier forms died silently instead. `head -1` after `grep -v '^#'`
  # returned 1 on an all-comment message, so under `set -e` the assignment
  # killed the script and the hook refused the commit with no output at all;
  # and `grep | head -1` dies of SIGPIPE when grep outruns head, which
  # `pipefail` reports as the failure of a command that did its job. `-m1`
  # removes the pipe, `|| true` the no-match case.
  subject="$(grep -m1 -vE '^[[:space:]]*$' "$MSG_FILE" || true)"
  source_desc="staged commit message"

  if [[ "$subject" == \#* ]]; then
    fail "the first line of the commit message is a comment"
    note "source: $source_desc ($MSG_FILE)"
    note "git keeps it as the subject under -m/-F and strips it when editing,"
    note "so what would land is ambiguous. Put the subject on the first line."
    finish
  fi
else
  if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
    skip "commit message (no HEAD and no file given)"
    finish
  fi
  # ⚠️ No comment-stripping here. `git log -1 --pretty=%s` is already the
  # cleaned subject, and `git commit -m '#123: …'` stores that verbatim —
  # `-m` uses cleanup=whitespace, which does not strip comments. Treating a
  # leading `#` as a comment in this mode reported "no subject" for a commit
  # whose subject was plainly there.
  subject="$(git log -1 --pretty=%s)"
  source_desc="HEAD"
fi

if [[ -z "${subject//[[:space:]]/}" ]]; then
  fail "the commit message has no subject"
  note "source: $source_desc (${MSG_FILE:-HEAD})"
  note "every line is blank or a comment, so there is nothing to check"
  finish
fi

# --- exemptions, each with a reason -----------------------------------------
#
# Revert subjects are generated by git and quoting the reverted subject inside
# them would nest quotes. The reverted commit already carries a task ID.
if [[ "$subject" == Revert\ * ]]; then
  ok "commit subject is a revert (exempt)"
  finish
fi

# fixup!/squash! are rewritten by an interactive rebase before they land, so the
# subject that will exist is the target commit's, which was already checked.
if [[ "$subject" == fixup!* || "$subject" == squash!* ]]; then
  ok "commit subject is a fixup/squash marker (exempt)"
  finish
fi

# Merge commits should not exist: commits go directly to `main` and there are no
# feature branches. This is a warning rather than a failure because a merge can
# arrive from outside the normal path, and refusing it in the hook would leave
# no way to record that it happened.
if [[ "$subject" == Merge\ * ]]; then
  warn "merge commit — commits go directly to main and there are no feature branches"
  ok "commit subject is a merge (exempt)"
  finish
fi

# --- the rule ----------------------------------------------------------------

if [[ ! "$subject" =~ ^(M-?[0-9]+\.[0-9]+)(,\ *M-?[0-9]+\.[0-9]+)*:\ .+ ]]; then
  fail "commit subject must start with a backlog task ID, then ': '"
  note "got:      $subject"
  note "expected: M-1.6: add the commit-message gate"
  note "source:   $source_desc"
  finish
fi

# Every ID named, so a commit closing two tasks is still fully traceable. This
# is not an invitation to batch: non-negotiable 1 still says one task, one
# commit, and review is where that is enforced.
ids="$(printf '%s' "$subject" | sed -E 's/:.*//' | tr ',' ' ')"

known="$(known_task_ids)"
if [[ -z "$known" ]]; then
  skip "commit subject IDs (backlog has no task table yet)"
  finish
fi

for id in $ids; do
  # ⚠️ `-F`, and a here-string rather than `printf | grep`. `-F` is
  # defense in depth rather than a live bug here — `$id` can only be
  # something the subject regex above already matched
  # (`M-?[0-9]+\.[0-9]+`), so it never carries a regex metacharacter the
  # way a hand-written review artifact's `task_id` could — but the
  # here-string is a real fix: `grep -qx` exits at the first match,
  # `printf`'s remaining write can then SIGPIPE, and `pipefail` reports
  # that early exit as failure, misreporting a real, listed task id as
  # unlisted. `M-1.48`: the same site `M-1.38` fixed in `check-reviewed.sh`
  # and `M-1.37` fixed in `check-milestone-review.sh`, missed here until
  # M-1.38's own review found it. See `portability.md`'s "Shell scripting"
  # section (rules 21-22) for the general idiom.
  if grep -qxF "$id" <<< "$known"; then
    ok "commit subject names $id, which the backlog lists"
  else
    fail "commit subject names $id, which the backlog does not list"
    note "add the task to docs/internal/product/backlog.md, or fix the ID"
  fi
done

# The subject after the ID has to say something. `M-1.6: wip` passes the regex
# and tells a future reader nothing.
#
# ## Why a denylist and not a length
#
# The first version of this check required ten characters, and the first thing
# it rejected was `M-1.2: mission` — an accurate one-word subject for a commit
# that adds mission.md. Length is a proxy for meaning and a poor one: it accepts
# `M-1.6: fix the thing` and rejects `M-1.2: mission`.
#
# So the rule names the words that actually carry no information. Four
# characters is only a floor against a stray keystroke.
text="$(printf '%s' "$subject" | sed -E 's/^[^:]*:[[:space:]]*//')"
first_word="$(printf '%s' "$text" | tr '[:upper:]' '[:lower:]' | awk '{print $1}')"

case "$first_word" in
  wip|fix|fixes|fixed|update|updates|updated|changes|changed|stuff|misc|temp|tmp|test|tests|cleanup|refactor)
    fail "commit subject starts with '$first_word', which says nothing about what changed"
    note "got: $text"
    note "say what changed, not that something did"
    ;;
esac

if (( ${#text} < 4 )); then
  fail "commit subject text is too short to be useful: '$text'"
fi

if (( ${#subject} > 72 )); then
  warn "commit subject is ${#subject} chars; 72 keeps 'git log --oneline' readable"
fi

finish
