#!/usr/bin/env bash
# The commit subject names a task the backlog actually lists. `M-1.6`.
#
#   scripts/check-commit-msg.sh <file>    the commit-msg hook path
#   scripts/check-commit-msg.sh           checks HEAD instead
#
# Non-negotiable 1 says one task equals one commit equals one change that leaves
# the tree green. This holds the traceable half: history stays resolvable to the
# plan, so `git log` answers "why does this exist" without archaeology.
#
# ## Why the ID must exist in the backlog rather than merely look like one
#
# A regex alone accepts `M-9.99`, which resolves to nothing. The point of the ID
# is the link, and a link to a task nobody wrote is worse than no ID because it
# reads as traceable. So the backlog is the authority and this script does not
# keep its own list.
#
# ## What it deliberately does not check
#
# Whether the commit actually *does* what the task says. No script reads intent,
# and pretending otherwise would make this a rule people route around. That
# belongs to review.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

cd "$REPO_ROOT"

MSG_FILE="${1:-}"

if [[ -n "$MSG_FILE" ]]; then
  [[ -f "$MSG_FILE" ]] || { fail "commit message file not found: $MSG_FILE"; finish; }
  subject="$(head -1 "$MSG_FILE")"
  source_desc="staged commit message"
else
  if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
    skip "commit message (no HEAD and no file given)"
    finish
  fi
  subject="$(git log -1 --pretty=%s)"
  source_desc="HEAD"
fi

# Comment lines are stripped by git before the message is used; if the first
# line is one, the real subject is the first line that is not.
if [[ "$subject" == \#* ]]; then
  subject="$(grep -v '^#' "$MSG_FILE" | head -1)"
fi

# --- exemptions, each with a reason -----------------------------------------
#
# Revert subjects are generated by git and quoting the reverted subject inside
# them would nest quotes. The reverted commit already carries a task ID.
if [[ "$subject" == Revert\ * ]]; then
  ok "commit subject is a revert (exempt)"
  finish
fi

# fixup!/squash! are rewritten by an interactive rebase before they land, so the
# subject that will exist is the target commit's, which was already checked.
if [[ "$subject" == fixup!* || "$subject" == squash!* ]]; then
  ok "commit subject is a fixup/squash marker (exempt)"
  finish
fi

# Merge commits should not exist: commits go directly to `main` and there are no
# feature branches. This is a warning rather than a failure because a merge can
# arrive from outside the normal path, and refusing it in the hook would leave
# no way to record that it happened.
if [[ "$subject" == Merge\ * ]]; then
  warn "merge commit — commits go directly to main and there are no feature branches"
  ok "commit subject is a merge (exempt)"
  finish
fi

# --- the rule ----------------------------------------------------------------

if [[ ! "$subject" =~ ^(M-?[0-9]+\.[0-9]+)(,\ *M-?[0-9]+\.[0-9]+)*:\ .+ ]]; then
  fail "commit subject must start with a backlog task ID, then ': '"
  note "got:      $subject"
  note "expected: M-1.6: add the commit-message gate"
  note "source:   $source_desc"
  finish
fi

# Every ID named, so a commit closing two tasks is still fully traceable. This
# is not an invitation to batch: non-negotiable 1 still says one task, one
# commit, and review is where that is enforced.
ids="$(printf '%s' "$subject" | sed -E 's/:.*//' | tr ',' ' ')"

known="$(known_task_ids)"
if [[ -z "$known" ]]; then
  skip "commit subject IDs (backlog has no task table yet)"
  finish
fi

for id in $ids; do
  if printf '%s\n' "$known" | grep -qx "$id"; then
    ok "commit subject names $id, which the backlog lists"
  else
    fail "commit subject names $id, which the backlog does not list"
    note "add the task to docs/internal/product/backlog.md, or fix the ID"
  fi
done

# The subject after the ID has to say something. `M-1.6: wip` passes the regex
# and tells a future reader nothing.
#
# ## Why a denylist and not a length
#
# The first version of this check required ten characters, and the first thing
# it rejected was `M-1.2: mission` — an accurate one-word subject for a commit
# that adds mission.md. Length is a proxy for meaning and a poor one: it accepts
# `M-1.6: fix the thing` and rejects `M-1.2: mission`.
#
# So the rule names the words that actually carry no information. Four
# characters is only a floor against a stray keystroke.
text="$(printf '%s' "$subject" | sed -E 's/^[^:]*:[[:space:]]*//')"
first_word="$(printf '%s' "$text" | tr '[:upper:]' '[:lower:]' | awk '{print $1}')"

case "$first_word" in
  wip|fix|fixes|fixed|update|updates|updated|changes|changed|stuff|misc|temp|tmp|test|tests|cleanup|refactor)
    fail "commit subject starts with '$first_word', which says nothing about what changed"
    note "got: $text"
    note "say what changed, not that something did"
    ;;
esac

if (( ${#text} < 4 )); then
  fail "commit subject text is too short to be useful: '$text'"
fi

if (( ${#subject} > 72 )); then
  warn "commit subject is ${#subject} chars; 72 keeps 'git log --oneline' readable"
fi

finish
